name: CI/CD Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push CodeGen Service
        uses: docker/build-push-action@v5
        with:
          context: ./code-gen
          file: ./code-gen/Dockerfile
          push: true
          tags: paritoshvikram/code_gen_hld:latest

      - name: Build and Push Infra Service
        uses: docker/build-push-action@v5
        with:
          context: ./infra
          file: ./infra/Dockerfile
          push: true
          tags: paritoshvikram/infra:latest
