apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app # Must match the name in the base deployment
spec:
  template:
    spec:
      containers:
      - name: fastapi-container # Must match the container name
        env:
        - name: DEBUG_MODE
          value: "true"
        resources: # Example: set lower resource limits for dev
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"